### ISSUE TITLE
timer is not visible

### ISSUE THREAD

**Issue by saumyas6933** [martinlindhe/timer#2]
after running the app only icon is showing. timer is not started.
![screen shot 2018-05-05 at 6 08 11 pm](https://user-images.githubusercontent.com/38682610/39663403-8cae5bc6-5090-11e8-9687-0f85ec788f8d.png)
please help.

**Comment by martinlindhe** [comment]
The timer is not shown in Windows due to limitations of what can be placed in the system tray. This functionality is only available in macOS and Linux.

**Comment by martinlindhe** [comment]
You need to right click the app icon and use the menu to start a timer.

**Comment by saumyas6933** [comment]
I tried to run it at macos and Linux. In Linux the menu is there but on mac
there isn't even menu, only icon of stopwatch shows.

**Comment by martinlindhe** [comment]
For macOS, you need to build an application bundle for it to work properly, see https://github.com/martinlindhe/timer#macos

**Comment by saumyas6933** [comment]
Ok i will see to it.

Thanks.

**Comment by martinlindhe** [comment]
Did you figure it out?

**Comment by martinlindhe** [comment]
Closing this, please open a new issue if you still need assistance.
